# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 260f30f1957474d00d655301cdae795b771d2ce2c3f6ffafd46e9b9ed1faac56c0ed55a7b36a93c4cd0e66989223e4d83e96b5635f88e656a33c047f345cca68

test:
  secret_key_base: 0283029c7b1b3695a3658fbb071a9133d7981cfb5a6dfbfc596edc4b6f46c498006adc1409ec2cbac0df1edbd58847b0d0f11245c87f5b6542686d33071002ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
